// Custom Worker entrypoint for UptimeFlare.
// Combines the OpenNext Next.js app (fetch handler + static assets) with the
// monitoring cron (scheduled handler) and the RemoteChecker Durable Object.

// @ts-expect-error - generated by `opennextjs-cloudflare build`
import openNextWorker from '../../.open-next/worker.js'
import monitoringWorker, { RemoteChecker } from './index'

export { RemoteChecker }

// Re-export OpenNext's internal Durable Objects so its caching features keep working.
// @ts-expect-error - generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../../.open-next/worker.js'

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response> {
    return openNextWorker.fetch(request, env, ctx)
  },
  async scheduled(controller: ScheduledEvent, env: CloudflareEnv, ctx: ExecutionContext): Promise<void> {
    await monitoringWorker.scheduled(controller, env as any, ctx)
  },
}
