name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install packages
        run: |
          npm ci
          npm ci --prefix worker

      - name: Run unit tests
        run: npm test

      - name: Type-check Worker
        run: npx tsc --noEmit -p tsconfig.json
        working-directory: worker

      - name: Build status page
        run: npm run build
